apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy-default-jaeger.json
  - deploy-otel-demo-grafana.json
  - deploy-otel-demo-otel-collector.json
  - deploy-otel-demo-prometheus.json
  - ing-default-otel-demo-ingress.json
  - sts-default-opensearch.json
