apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-demo
resources:
  - deploy-grafana.json
  - deploy-otel-collector.json
  - deploy-prometheus.json
  - svc-grafana.json
  - svc-otel-collector.json
  - svc-prometheus.json
